### ISSUE TITLE
SIP Plugins to OSPy Plugins

### ISSUE THREAD

**Issue by RRIoT** [martinpihrt/OSPy-plugins#1]
Hi Martin.

Your version of OSPy is Awesome. Thank you very much for your time spent on it.

Is it possible to convert SIP's Plugins to work on OSPy.
I have a Taio Smart Sprinkler Board and would like to test and use it with OSPy with SIP's Relay_16 Plugin.

Thank you very much,
Kind Regards
Craig. (Rakaia, New Zealand)

**Comment by martinpihrt** [comment]
Hi Craig,
the plugin will not be a problem to porting in to OSPy, I do not know if the GPIO pins  conflict with something in other plug-in (questions: is posible set outputs on other pins - if it was a problem?)

Sincerely Martin.
(Czech Republic city Pilsen "beer city")

**Comment by RRIoT** [comment]
HI Martin

Thank You for the quick reply.

Thank you so much for porting them.

Is it possible to port a couple more of SIP's Plugins please.

Link below, links to the Taio Smart Sprinkler Board Hardware and Pin layout
of the board.

It shows what GPIO pins it uses.

https://www.tiaowiki.com/w/TIAO_Smart_Sprinkler_Pi_Hardware_Layout

Thank you again.

Have a great day

Kind Regards
Craig
___________________________________

Craig Riddle

Riddle's Ranch.
Riddle's Ranch IoT.

251 Rakaia Barrhill Methven Road
R.D 14
Rakaia
New Zealand.

E. craigriddle7@gmail.com

**Comment by martinpihrt** [comment]
Hi Craig,
in OSPy is new plugin: https://github.com/martinpihrt/OSPy-plugins/tree/master/plugins/relay_16
try it!
![snimek obrazovky 107](https://user-images.githubusercontent.com/7847139/41041734-2b1df5b4-69a0-11e8-88ac-48b076b6e494.png)

Regards
Martin

**Comment by RRIoT** [comment]
Hi Martin.

So Sorry for the Late Reply.

Had a really busy three weeks.

Works Awesomely.

Are you able to also bring across the following Plugins from SIP

https://github.com/Dan-in-CA/sip_plugins/tree/master/keypad_plugin
https://github.com/Dan-in-CA/sip_plugins/tree/master/pump_control
https://github.com/Dan-in-CA/sip_plugins/tree/master/buzzer
https://github.com/Dan-in-CA/sip_plugins/tree/master/relay_board
https://github.com/Dan-in-CA/sip_plugins/tree/master/proto
https://github.com/Dan-in-CA/sip_plugins/tree/master/pcf_8591_adj
https://github.com/Dan-in-CA/sip_plugins/tree/master/cli_control
https://github.com/Dan-in-CA/sip_plugins/tree/master/ssd1306

I believe that these will be useful Plugins.

Thank You Again for all your Hard Work. This Project is Awesome.

Kind Reagrds
Craig Riddle
Rakaia, New Zealand.

**Comment by martinpihrt** [comment]
Hi Craig,
relay_board and pcf_8591_adj - is long already in ospy...
proto plugin - therefore, the plugin is not a plugin, but a tutorial for all. How to work on own a plugins...

Maybe done this plugin:
https://github.com/Dan-in-CA/sip_plugins/tree/master/cli_control

For these plugins I do not have hardware and I do not plan to produce it...
https://github.com/Dan-in-CA/sip_plugins/tree/master/keypad_plugin
https://github.com/Dan-in-CA/sip_plugins/tree/master/pump_control
https://github.com/Dan-in-CA/sip_plugins/tree/master/buzzer
https://github.com/Dan-in-CA/sip_plugins/tree/master/ssd1306

**Comment by RRIoT** [comment]
Hi Martin.

Thank you very much for your time.

I would be able happy to convert the plugins and make my own, but I am not
sure how to do this with the plugins for OSPy.

The plugins on SIP look different on how yours and Rimco's are.

Do you have a tutorial on how to do OSPy's plugins, so I can make or even
port them from SIP.

Thank You Again for your time and advice.

Have a great day

Kind Regards
Craig.

Rakaia, New Zealand.

**Comment by martinpihrt** [comment]
Hi Craig,
I translated plugins from SIP into OSPY manually. The differences between SIP and OSPy are enormous...
I have no instructions on how to create new plugins :-(
Do you have the necessary hardware for the remaining SIP plugins? can i create other plugins from SIP and you try it?
It's possible to help you with new plugins (if it's in my power - I'm not a guru programmer)...

Best regards
Martin
