### ISSUE TITLE
REF: plugins/lcd_display/__init__.py. Can not find LCD if address is 0x27

### ISSUE THREAD

**Issue by ITDPG4** [martinpihrt/OSPy-plugins#2]
The LCD plugin should look at address 0x27 according info, but it only found my LCD on 0x27 after a change in _init_.py.

Changed:
def find_lcd_address():
search_range = {addr: 'PCF8574' for addr in range(32, 39)}

To:
def find_lcd_address():
search_range = {addr: 'PCF8574' for addr in range(32, 40)}

**Comment by martinpihrt** [comment]
Hi,
thank you.
Fixed
MP
