### ISSUE TITLE
error in Water Level by Netatmo Plugin

### ISSUE THREAD

**Issue by Dalmapalma** [martinpihrt/OSPy-plugins#3]
Hi,

I just installed OSPy and tried to install the water Level Netatmo plugin. Unfortunately I alsoway returns an error. Seems that it somehow tries to access Weather Underground API.

`Weather-based water level plug-in: Traceback (most recent call last): File "/home/pi/OSPy/plugins/weather_based_water_level_netatmo/__init__.py", line 114, in run history = weather.get_wunderground_history(plugin_options['days_history']) File "/home/pi/OSPy/ospy/weather.py", line 280, in _deprecated raise Exception('This interface was removed because Weather Underground API has stopped, please update the plug-in!') Exception: This interface was removed because Weather Underground API has stopped, please update the plug-in!`

**Comment by martinpihrt** [comment]
Hi,
thank you for the warning. I'll try to fix the plugin.
Martin

**Comment by martinpihrt** [comment]
Fixed, try it!
Martin

**Comment by Dalmapalma** [comment]
thanks a lot :-) it works 👍
