### ISSUE TITLE
MQTT does not start

### ISSUE THREAD

**Issue by Dalmapalma** [martinpihrt/OSPy-plugins#4]
Hi,

Just installed the MQTT Plugin and entered all the details to my MQTT server. Unfortunately it does not start. I get always this message `Paho-mqtt is not installed.
Please wait installing paho-mqtt...`.

I'm waiting now already 2 weeks but still not installed. :-)

**Comment by martinpihrt** [comment]
Hi, please enable saving "debugging" in the OSPY settings and enable the extension: system debug. Then delete the MQTT extension, install the MQTT extension. Try to start the MQTT extension. Then send me the system debug record to admin@pihrt.com. I'll see if I can find anything from the record.
Thank you, Martin

**Comment by martinpihrt** [comment]
Hi try it - i fixed it...
Martin

**Comment by Dalmapalma** [comment]
Hi Martin,

it works perfectly!!! 

Thank you.
