### ISSUE TITLE
MQTT Zone Broadcaster can't be enabled after upgrade

### ISSUE THREAD

**Issue by Dalmapalma** [martinpihrt/OSPy-plugins#5]
Hi Martin,

I've updated the plugin MQTT and MQTT Zone Broadcaster. After that the plugin Zone Broadcaster can not be enabled. 

I've already send you the log file. Maybe you can figure out what happened.

Thanks in advance and kind regards,
Branimir

**Comment by martinpihrt** [comment]
Hi Branimir,
Fixing my mistake :-(
I apologize for the late reply, but I was on vacation without the Internet.
Try it.
Martin
