### ISSUE TITLE
Plugin Button Control

### ISSUE THREAD

**Issue by ITDPG4** [martinpihrt/OSPy-plugins#6]
Using button 1 to reboot or button 2 to shutdown RPi gives error that global commands reboot and shutdown are not known. When editing in init.py: 
"from ospy.helpers import datetime_string"
to a previous version:
"from ospy.helpers import get_rpi_revision, datetime_string, reboot, restart, poweroff" buttons work OK again

**Comment by martinpihrt** [comment]
thank you for reporting, corrected.
Martin
