### ISSUE TITLE
Weatherstation Mqtt 

### ISSUE THREAD

**Issue by Marmi86** [martinpihrt/OSPy-plugins#7]
Hello nice project, 
Can I use my locale weatherstation with the Mqtt protocol?

Or how could I integrate my local weather station, use a Homematic

Marco

**Comment by martinpihrt** [comment]
Hi Marco,
I do not understand the request. Do I mean that you want to send data from your weather station to the OSPy or has OSPy send data to the weather station. The following MQTT extensions for OSPy are currently available:
[https://github.com/martinpihrt/OSPy-plugins/tree/master/plugins/mqtt](https://github.com/martinpihrt/OSPy-plugins/tree/master/plugins/mqtt)
Can send the OSPy status of the system and at the same time receive station control in manual mode.
[https://github.com/martinpihrt/OSPy-plugins/tree/master/plugins/mqtt_zones](https://github.com/martinpihrt/OSPy-plugins/tree/master/plugins/mqtt_zones)
For broadcast the current status of all zones to MQTT broker.
And 
[https://github.com/martinpihrt/OSPy-plugins/tree/master/plugins/mqtt_runonce](https://github.com/martinpihrt/OSPy-plugins/tree/master/plugins/mqtt_runonce)
Allows runonce programs to be set over MQTT. The received message is a sheet that contains: station number, time in seconds.
However, this extension is not yet complete.
MQTT in OSPy at the moment can only send its status and station statuses to the broker. At the same time it can receive the status of broker stations for the control of subordinate systems (main ospy controls more secondary ospy). 

The answer to the question: if you want to use the "Homematic" weather station in the OSPy system, then this is not possible at the moment.
Best regard
Martin
