### ISSUE TITLE
Irrigation based on ETo 

### ISSUE THREAD

**Issue by garudaonekh** [martinpihrt/OSPy-plugins#8]
Hi,
ETo is dynamic and change all the time. How do we manage this in your code?

Thanks

**Comment by martinpihrt** [comment]
Hi,
Extensions can be used in the system:
(a) using a "netatmo" weather station and precipitation measurements
b) using the weather forecast - Dark Sky service
c) manually on the home page (by pressing a button and entering a value) it is possible to shorten or lengthen all programs in% of the time
d) the system has a rain sensor (input) with which programs can be blocked

another method is not yet available
Martin

**Comment by garudaonekh** [comment]
I mean the use dynamic ETo that we retrieved from weather forecast data. Right now, I have to go to change ETo by hand right?

**Comment by martinpihrt** [comment]
if you use the dark sky service (their API is entered into the OSPy), then the data is adjusted with respect to the weather forecast in the OSPy itself (ETo). Retrieving data from other services is not available at this time.
